# Generated by Django 4.0.1 on 2022-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
