# Generated by Django 4.0.1 on 2022-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
